### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by Wicpar** [austinleroy/webm-iterable#2]
Hi, how would one go about implementing streaming for this crate ? I have a stream of non structured matroska chunks (cut randomly from one big file, its entirety is guaranteed to be a valid file and no packets can be lost) and need to convert it to MP4 with the least amount of latency ? (video is AVC1 and audio will be converted manually to a supported codec from PCM)

**Comment by austinleroy** [comment]
Sorry for the delay - my day job has been keeping me busy!  I see you found the ebml-iterable crate and created a PR in that repo (which is the correct place to add unsized EBML support).  I will try to make time to start reviewing it today.
