### ISSUE TITLE
Feature Request - Ability to force content size byte count for element

### ISSUE THREAD

**Issue by wcork** [austinleroy/webm-iterable#8]
This is related to #7 .

In other webm muxers, they force the Segment Content size to 8 bytes so that the Seek Head position is known before writing Cues or calculating offsets from Clusters.

In the non-streaming case, many players parse the entire file, but DASH.js or any streaming configuration will have issues if you remux with this iterator.

Example:
```
[Segment (ElementID:0x18538067, ContentSize:0x0000000001baaa1f)] = 29010463 bytes.
```

See `bool Segment::Finalize()` in the [libwebm](https://github.com/webmproject/libwebm/blob/d411c8668dc226d9a3c7433c560dedfcc46fc69c/mkvmuxer/mkvmuxer.cc#L3220C27-L3220C27) muxer

If maybe a selection isn't possible, maybe it should always be the case to use 8 bytes for Segment sections?

**Comment by austinleroy** [comment]
This makes sense - it makes it a lot easier to calculate byte offsets if you can rely on the size marker being a set length.  My use cases so far with this library haven't worried about Seek positions, but I see the need for such a feature.

I made some changes to implement this and pushed them up in version 0.6.0.  Let me know if this works, or if you have any ideas that could make it more ergonomic.  There's a new method `write_advanced` that allows you to pass in an option to specify the byte length of the element size.

**Comment by austinleroy** [comment]
Closing this issue as there hasn't been any feedback (assuming the updates in version 0.6.0 were adequate)
